# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sales_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sales_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sales_data.proto\x12\nsales_data\"F\n\x0eSalesDataChunk\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nchunk_data\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"\xa0\x01\n\x0fProcessResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x14\n\x0c\x64ownload_url\x18\x04 \x01(\t\x12\x12\n\ntotal_rows\x18\x05 \x01(\x05\x12\x19\n\x11total_departments\x18\x06 \x01(\x05\x12\x17\n\x0fprocessing_time\x18\x07 \x01(\x01\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"l\n\x11JobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x10\n\x08progress\x18\x04 \x01(\x05\x12\x14\n\x0c\x64ownload_url\x18\x05 \x01(\t\"!\n\x0f\x44ownloadRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"M\n\x10\x44ownloadResponse\x12\x14\n\x0c\x64ownload_url\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x03\x32\xfd\x01\n\x12SalesDataProcessor\x12M\n\x10ProcessSalesData\x12\x1a.sales_data.SalesDataChunk\x1a\x1b.sales_data.ProcessResponse(\x01\x12K\n\x0cGetJobStatus\x12\x1c.sales_data.JobStatusRequest\x1a\x1d.sales_data.JobStatusResponse\x12K\n\x0e\x44ownloadResult\x12\x1b.sales_data.DownloadRequest\x1a\x1c.sales_data.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sales_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALESDATACHUNK']._serialized_start=32
  _globals['_SALESDATACHUNK']._serialized_end=102
  _globals['_PROCESSRESPONSE']._serialized_start=105
  _globals['_PROCESSRESPONSE']._serialized_end=265
  _globals['_JOBSTATUSREQUEST']._serialized_start=267
  _globals['_JOBSTATUSREQUEST']._serialized_end=301
  _globals['_JOBSTATUSRESPONSE']._serialized_start=303
  _globals['_JOBSTATUSRESPONSE']._serialized_end=411
  _globals['_DOWNLOADREQUEST']._serialized_start=413
  _globals['_DOWNLOADREQUEST']._serialized_end=446
  _globals['_DOWNLOADRESPONSE']._serialized_start=448
  _globals['_DOWNLOADRESPONSE']._serialized_end=525
  _globals['_SALESDATAPROCESSOR']._serialized_start=528
  _globals['_SALESDATAPROCESSOR']._serialized_end=781
# @@protoc_insertion_point(module_scope)
