# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import sales_data_pb2 as sales__data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sales_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SalesDataProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSalesData = channel.stream_unary(
                '/sales_data.SalesDataProcessor/ProcessSalesData',
                request_serializer=sales__data__pb2.SalesDataChunk.SerializeToString,
                response_deserializer=sales__data__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/sales_data.SalesDataProcessor/GetJobStatus',
                request_serializer=sales__data__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=sales__data__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.DownloadResult = channel.unary_unary(
                '/sales_data.SalesDataProcessor/DownloadResult',
                request_serializer=sales__data__pb2.DownloadRequest.SerializeToString,
                response_deserializer=sales__data__pb2.DownloadResponse.FromString,
                _registered_method=True)


class SalesDataProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessSalesData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesDataProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSalesData': grpc.stream_unary_rpc_method_handler(
                    servicer.ProcessSalesData,
                    request_deserializer=sales__data__pb2.SalesDataChunk.FromString,
                    response_serializer=sales__data__pb2.ProcessResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=sales__data__pb2.JobStatusRequest.FromString,
                    response_serializer=sales__data__pb2.JobStatusResponse.SerializeToString,
            ),
            'DownloadResult': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadResult,
                    request_deserializer=sales__data__pb2.DownloadRequest.FromString,
                    response_serializer=sales__data__pb2.DownloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sales_data.SalesDataProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sales_data.SalesDataProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SalesDataProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSalesData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/sales_data.SalesDataProcessor/ProcessSalesData',
            sales__data__pb2.SalesDataChunk.SerializeToString,
            sales__data__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales_data.SalesDataProcessor/GetJobStatus',
            sales__data__pb2.JobStatusRequest.SerializeToString,
            sales__data__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales_data.SalesDataProcessor/DownloadResult',
            sales__data__pb2.DownloadRequest.SerializeToString,
            sales__data__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
